version: '3'
volumes:
   data:
   m2:
services:
   database:
      image: postgres:11.3
      environment:
         - POSTGRES_DB=shorturl
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=password
      volumes:
         - data:/var/lib/postgresql/data
   backend:
      image: openjdk:8
      restart: on-failure
      volumes:
         - .:/app
         - m2:/root/.m2
      working_dir: /app
      command: mvn clean spring-boot:run
      ports:
         - 80:8090
      depends_on:
         - database
